Algoritmo "Exemplo 1 Tabela"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Raiz 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/05/2020
Var
// Seção de Declarações das variáveis 
X, Y :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
X := 5
Y := 0

ENQUANTO (X > 2) FACA
         ESCREVA(X)
         Y := Y + X
         X := X - 1
FIMENQUANTO

Fimalgoritmo