Algoritmo "Exemplo PARA Tabela 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Raiz 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/10/2020
Var
// Seção de Declarações das variáveis 
x, y, i :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x := 4
y := x + 2
PARA i DE 1 ATE x - 1 FACA
     ESCREVAL(x, " - ", y)
     y := y + i
FIMPARA


Fimalgoritmo