Algoritmo "teste"
// Disciplina  : [Linguagem e Lógica de programaçao] 
// Professor(a): Antonio     
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/06/2015
var
// Seção de Declarações das variáveis 
    x: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      x := x + 1
      Escreval(x)

fimalgoritmo