Algoritmo "Exercicio 4 Trabalho"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Raiz 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2020
Var
// Seção de Declarações das variáveis 
custo, convite, qtd: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
LEIA(custo)
LEIA(convite)

qtd := custo/convite

ESCREVA(qtd)

Fimalgoritmo